Non-commercial Use License

Copyright (c) 2021 Siemens Technology

This software, along with associated documentation files (the "Software"), is 
provided for the sole purpose of providing Proof of Concept. Any commercial 
uses of the Software including, but not limited to, the rights to sublicense, 
and/or sell copies of the Software are prohibited and are subject to a 
separate licensing agreement with Siemens. This software may be proprietary 
to Siemens and may be covered by patent and copyright laws. Processes 
controlled by the Software are patent pending.

The above copyright notice and this permission notice shall remain attached 
to the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

In [1]:
import os, sys
THIS_DIR = os.path.abspath('')
PARENT_DIR = os.path.dirname(os.path.abspath(''))
sys.path.append(PARENT_DIR)
import pickle
from argparse import ArgumentParser

from datasets.datasets import RigidBodyDataset
from systems.bouncing_mass_points import BouncingMassPoints

import torch
import torch.nn as nn
import torch.nn.functional as F
import json
from trainer import Model

In [15]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_CLNNwC_N800",
    "version_0",
    "epoch=892.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [1.0000],
        [1.0000],
        [1.0002],
        [1.0003]], grad_fn=<DivBackward0>)

In [16]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_mujoco_CLNNwC_N800",
    "version_0",
    "epoch=997.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [1.0000],
        [0.9993],
        [0.9991],
        [0.9989]], grad_fn=<DivBackward0>)

In [17]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_CHNNwC_N800",
    "version_0",
    "epoch=909.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [0.9998],
        [1.0000],
        [1.0000],
        [1.0000]], grad_fn=<DivBackward0>)

In [18]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_mujoco_CHNNwC_N800",
    "version_0",
    "epoch=997.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [1.0004],
        [0.9994],
        [0.9999],
        [0.9997]], grad_fn=<DivBackward0>)

In [19]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_hetero_g0_CLNNwC_N800",
    "version_0",
    "epoch=956.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

406 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[ 1.0000],
        [ 2.0001],
        [ 6.0036],
        [ 8.0014],
        [10.0024]], grad_fn=<DivBackward0>)

In [20]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_hetero_g0_mujoco_CLNNwC_N800",
    "version_0",
    "epoch=870.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [1.9998],
        [6.0004],
        [8.0033],
        [9.9997]], grad_fn=<DivBackward0>)

In [21]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_hetero_g0_CHNNwC_N800",
    "version_0",
    "epoch=956.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

406 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[ 1.0000],
        [ 2.0005],
        [ 6.0020],
        [ 8.0015],
        [10.0029]], grad_fn=<DivBackward0>)

In [22]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_hetero_g0_mujoco_CHNNwC_N800",
    "version_0",
    "epoch=870.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[ 1.0000],
        [ 2.0002],
        [ 6.0001],
        [ 7.9985],
        [10.0010]], grad_fn=<DivBackward0>)

In [6]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BD5_hetero_g0_CLNNwC_N800",
    "version_2",
    "epoch=990.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


In [7]:
model.model.m_params

ParameterDict(  (2): Parameter containing: [torch.FloatTensor of size 5x3])

In [8]:
learned_mass = torch.exp(model.model.m_params["2"])

In [9]:
learned_mass / learned_mass[0,0]

tensor([[1.0000e+00, 1.0746e-02, 1.0318e-02],
        [3.3003e+00, 2.2107e-02, 1.5545e-02],
        [1.0510e+01, 3.2041e-02, 2.9512e-02],
        [1.4014e+01, 3.9885e-02, 4.2086e-02],
        [1.7804e+01, 5.2160e-02, 6.3105e-02]], grad_fn=<DivBackward0>)

In [10]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_CLNNwC_N800",
    "version_0",
    "epoch=939.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)

404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


In [11]:
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

tensor([[1.0000],
        [0.6500],
        [0.7502]], grad_fn=<DivBackward0>)

In [23]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_mujoco_CLNNwC_N800",
    "version_0",
    "epoch=994.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [0.6500],
        [0.7521]], grad_fn=<DivBackward0>)

In [24]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_CHNNwC_N800",
    "version_1",
    "epoch=950.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [0.6499],
        [0.7500]], grad_fn=<DivBackward0>)

In [25]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_mujoco_CHNNwC_N800",
    "version_0",
    "epoch=948.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


tensor([[1.0000],
        [0.6503],
        [0.7526]], grad_fn=<DivBackward0>)

In [26]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_CLNNwC_N800",
    "version_0",
    "epoch=969.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.


tensor([[1.0000],
        [2.0006],
        [1.4990]], grad_fn=<DivBackward0>)

In [27]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CLNNwC_N800",
    "version_0",
    "epoch=979.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.


tensor([[1.0000],
        [2.0002],
        [1.5001]], grad_fn=<DivBackward0>)

In [28]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_CHNNwC_N800",
    "version_0",
    "epoch=983.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.


tensor([[1.0000],
        [1.9996],
        [1.4994]], grad_fn=<DivBackward0>)

In [29]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CHNNwC_N800",
    "version_0",
    "epoch=981.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
learned_mass = torch.exp(model.model.m_params["0"])
learned_mass / learned_mass[0]

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.


tensor([[1.0000],
        [2.0009],
        [1.5009]], grad_fn=<DivBackward0>)

In [12]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "Gyro_homo_cor1_mu0_CLNNwC_N800",
    "version_1",
    "last.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)

/home/desmond/.pyenv/versions/ode/lib/python3.8/site-packages/torch/serialization.py:658: SourceChangeWarning: source code of class 'models.impulse.ImpulseSolver' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.


In [13]:
learned_mass = torch.exp(model.model.m_params["3"])
learned_mass / learned_mass[0,0]

tensor([[1.0000, 0.9288, 0.9286, 0.8722]], grad_fn=<DivBackward0>)