Non-commercial Use License

Copyright (c) 2021 Siemens Technology

This software, along with associated documentation files (the "Software"), is 
provided for the sole purpose of providing Proof of Concept. Any commercial 
uses of the Software including, but not limited to, the rights to sublicense, 
and/or sell copies of the Software are prohibited and are subject to a 
separate licensing agreement with Siemens. This software may be proprietary 
to Siemens and may be covered by patent and copyright laws. Processes 
controlled by the Software are patent pending.

The above copyright notice and this permission notice shall remain attached 
to the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

In [1]:
import os, sys
PARENT_DIR = os.path.dirname(os.path.abspath(''))
sys.path.append(PARENT_DIR)
import pickle
from argparse import ArgumentParser

from datasets.datasets import RigidBodyDataset
from systems.rope_chain import RopeChain
from systems.bouncing_disks import BouncingDisks
from systems.bouncing_mass_points import BouncingMassPoints
from systems.elastic_rope import ElasticRope
from systems.gyroscope_with_wall import GyroscopeWithWall
from pytorch_lightning import seed_everything

import torch
import torch.nn as nn
import torch.nn.functional as F
import json
from trainer import Model

seed_everything(0)

import matplotlib.pyplot as plt
# plt.switch_backend("TkAgg")


def str_to_class(classname):
    return getattr(sys.modules[__name__], classname)

def utils(model, n_p_1=0):
    IP = "IPR" if hasattr(model.hparams, "is_mujoco_like") and model.hparams.is_mujoco_like else "IP"
    name = model.hparams.network_class + "_" + IP + "_" + model.hparams.body_kwargs_file
    # name = model.hparams.network_class + "_" + model.hparams.body_kwargs_file
    print(name)
    print(torch.exp(model.model.m_params[f"{n_p_1}"]))
    print("mu:", f"{F.relu(model.model.mu_params)}")
    print("cor:" + f"{F.hardsigmoid(model.model.cor_params)}")

In [2]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_mujoco_CLNNwC_N800_0.05",
    "version_0",
    "epoch=875.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor1_mu0
tensor([[1.1774],
        [0.7588],
        [0.8572]], grad_fn=<ExpBackward>)
mu: tensor([0.0036], grad_fn=<ReluBackward0>)
cor:tensor([1.], grad_fn=<HardsigmoidBackward>)


In [4]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_mujoco_CLNNwC_N800_0.01",
    "version_0",
    "epoch=319.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

/home/z0042y5x/.pyenv/versions/ode/lib/python3.8/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'models.impulse_mujoco.ImpulseSolverMujoco' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor1_mu0
tensor([[1.2073],
        [0.7846],
        [0.9072]], grad_fn=<ExpBackward>)
mu: tensor([0.0038], grad_fn=<ReluBackward0>)
cor:tensor([1.], grad_fn=<HardsigmoidBackward>)


In [5]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_CLNNwC_N800_0.05",
    "version_0",
    "epoch=875.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

/home/z0042y5x/.pyenv/versions/ode/lib/python3.8/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'models.impulse.ImpulseSolver' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IP_CP3_ground_homo_cor1_mu0
tensor([[1.2502],
        [0.8040],
        [0.8926]], grad_fn=<ExpBackward>)
mu: tensor([0.], grad_fn=<ReluBackward0>)
cor:tensor([0.9978], grad_fn=<HardsigmoidBackward>)


In [7]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_CLNNwC_N800_0.01",
    "version_0",
    "epoch=870.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IP_CP3_ground_homo_cor1_mu0
tensor([[1.2707],
        [0.8268],
        [0.9552]], grad_fn=<ExpBackward>)
mu: tensor([0.0009], grad_fn=<ReluBackward0>)
cor:tensor([1.], grad_fn=<HardsigmoidBackward>)


In [8]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CLNNwC_N800_0.05",
    "version_0",
    "epoch=830.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor0_mu0.5
tensor([[0.9240],
        [1.8191],
        [1.2828]], grad_fn=<ExpBackward>)
mu: tensor([0.4618], grad_fn=<ReluBackward0>)
cor:tensor([0.0608], grad_fn=<HardsigmoidBackward>)


In [9]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CLNNwC_N800_0.01",
    "version_0",
    "epoch=902.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor0_mu0.5
tensor([[0.9088],
        [1.8225],
        [1.3635]], grad_fn=<ExpBackward>)
mu: tensor([0.4959], grad_fn=<ReluBackward0>)
cor:tensor([0.0361], grad_fn=<HardsigmoidBackward>)


In [10]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_CLNNwC_N800_0.01",
    "version_0",
    "epoch=902.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IP_CP3_ground_homo_cor0_mu0.5
tensor([[0.6022],
        [1.2062],
        [0.8939]], grad_fn=<ExpBackward>)
mu: tensor([0.4951], grad_fn=<ReluBackward0>)
cor:tensor([0.0180], grad_fn=<HardsigmoidBackward>)


In [11]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_CLNNwC_N800_0.05",
    "version_0",
    "epoch=830.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IP_CP3_ground_homo_cor0_mu0.5
tensor([[0.6646],
        [1.3282],
        [0.7755]], grad_fn=<ExpBackward>)
mu: tensor([0.4353], grad_fn=<ReluBackward0>)
cor:tensor([0.0632], grad_fn=<HardsigmoidBackward>)


In [12]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_CLNNwC_N800_0.05",
    "version_0",
    "epoch=693.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IP_BM5_homo_cor1_mu0_g0
tensor([[0.9198],
        [1.0002],
        [1.0530],
        [1.1033],
        [1.0299]], grad_fn=<ExpBackward>)
mu: tensor([0.], grad_fn=<ReluBackward0>)
cor:tensor([0.0373], grad_fn=<HardsigmoidBackward>)


In [13]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_CLNNwC_N800_0.01",
    "version_0",
    "epoch=912.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IP_BM5_homo_cor1_mu0_g0
tensor([[0.9864],
        [0.9772],
        [1.0045],
        [0.9771],
        [0.9815]], grad_fn=<ExpBackward>)
mu: tensor([0.], grad_fn=<ReluBackward0>)
cor:tensor([0.9266], grad_fn=<HardsigmoidBackward>)


In [14]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_mujoco_CLNNwC_N800_0.01",
    "version_0",
    "epoch=991.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_BM5_homo_cor1_mu0_g0
tensor([[0.5413],
        [0.5435],
        [0.5364],
        [0.5364],
        [0.5395]], grad_fn=<ExpBackward>)
mu: tensor([0.0024], grad_fn=<ReluBackward0>)
cor:tensor([0.9712], grad_fn=<HardsigmoidBackward>)


In [15]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_mujoco_CLNNwC_N800_0.049",
    "version_0",
    "epoch=88.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_BM5_homo_cor1_mu0_g0
tensor([[1.0787],
        [1.0472],
        [1.0110],
        [0.9468],
        [1.1050]], grad_fn=<ExpBackward>)
mu: tensor([0.4460], grad_fn=<ReluBackward0>)
cor:tensor([0.2435], grad_fn=<HardsigmoidBackward>)


In [16]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CLNNwC_N800",
    "version_1",
    "epoch=887.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor0_mu0.5
tensor([[0.6685],
        [1.3373],
        [1.0028]], grad_fn=<ExpBackward>)
mu: tensor([0.4998], grad_fn=<ReluBackward0>)
cor:tensor([0.0067], grad_fn=<HardsigmoidBackward>)


In [17]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CLNNwC_N800",
    "version_2",
    "epoch=903.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor0_mu0.5
tensor([[0.9538],
        [1.9069],
        [1.4318]], grad_fn=<ExpBackward>)
mu: tensor([0.5006], grad_fn=<ReluBackward0>)
cor:tensor([0.1799], grad_fn=<HardsigmoidBackward>)


In [22]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CLNNwC_N800",
    "version_3",
    "epoch=867.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model)
F.softplus(model.model.impulse_solver.reg)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor0_mu0.5
tensor([[0.3854],
        [0.7703],
        [0.5791]], grad_fn=<ExpBackward>)
mu: tensor([0.4970], grad_fn=<ReluBackward0>)
cor:tensor([0.4525], grad_fn=<HardsigmoidBackward>)


tensor([0.6150], grad_fn=<SoftplusBackward>)

In [24]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "Gyro_homo_cor0.8_mu0.1_mujoco_CLNNwC_N800",
    "version_1",
    "epoch=937.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=3)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_Gyro_homo_cor0.8_mu0.1
tensor([[0.8956, 0.9002, 0.9001, 0.8640]], grad_fn=<ExpBackward>)
mu: tensor([0.0999], grad_fn=<ReluBackward0>)
cor:tensor([0.8113], grad_fn=<HardsigmoidBackward>)


In [25]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "Gyro_homo_cor0.8_mu0.1_mujoco_CLNNwC_N800",
    "version_2",
    "epoch=991.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=3)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_Gyro_homo_cor0.8_mu0.1
tensor([[0.0859, 0.4267, 0.4265, 0.4939]], grad_fn=<ExpBackward>)
mu: tensor([0.0995], grad_fn=<ReluBackward0>)
cor:tensor([0.8855], grad_fn=<HardsigmoidBackward>)


In [27]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "Gyro_homo_cor0.8_mu0.1_mujoco_CLNNwC_N800",
    "version_3",
    "epoch=964.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=3)
F.softplus(model.model.impulse_solver.reg)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_Gyro_homo_cor0.8_mu0.1
tensor([[0.1120, 0.3710, 0.3707, 0.4200]], grad_fn=<ExpBackward>)
mu: tensor([0.0998], grad_fn=<ReluBackward0>)
cor:tensor([0.8612], grad_fn=<HardsigmoidBackward>)


tensor([0.0619], grad_fn=<SoftplusBackward>)

In [2]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor0_mu0.5_mujoco_CLNNwC_N800",
    "version_6",
    "epoch=926.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=0)

404 out of 800 trajectories contains collision.
49 out of 100 trajectories contains collision.
49 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor0_mu0.5
tensor([[0.8381],
        [1.6767],
        [1.2578]], grad_fn=<ExpBackward>)
mu: tensor([0.5004], grad_fn=<ReluBackward0>)
cor:tensor([0.0209], grad_fn=<HardsigmoidBackward>)


In [3]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "CP3_ground_homo_cor1_mu0_mujoco_CLNNwC_N800",
    "version_6",
    "epoch=978.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=0)

404 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_CP3_ground_homo_cor1_mu0
tensor([[0.8494],
        [0.5525],
        [0.6390]], grad_fn=<ExpBackward>)
mu: tensor([0.0025], grad_fn=<ReluBackward0>)
cor:tensor([1.], grad_fn=<HardsigmoidBackward>)


In [5]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "BM5_homo_cor1_mu0_g0_mujoco_CLNNwC_N800",
    "version_4",
    "epoch=991.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=0)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_BM5_homo_cor1_mu0_g0
tensor([[0.4035],
        [0.4034],
        [0.4036],
        [0.4033],
        [0.4035]], grad_fn=<ExpBackward>)
mu: tensor([0.0002], grad_fn=<ReluBackward0>)
cor:tensor([0.9999], grad_fn=<HardsigmoidBackward>)


In [7]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "Gyro_homo_cor0.8_mu0.1_mujoco_CLNNwC_N800",
    "version_10",
    "epoch=698.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=3)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_Gyro_homo_cor0.8_mu0.1
tensor([[0.1643, 0.6858, 0.6857, 0.7875]], grad_fn=<ExpBackward>)
mu: tensor([0.0999], grad_fn=<ReluBackward0>)
cor:tensor([0.8215], grad_fn=<HardsigmoidBackward>)


In [8]:
checkpoint_path = os.path.join(
    PARENT_DIR,
    "logs",
    "Gyro_homo_cor0.8_mu0.1_mujoco_CLNNwC_N800",
    "version_10",
    "epoch=784.ckpt"
) 
model = Model.load_from_checkpoint(checkpoint_path)
utils(model, n_p_1=3)

405 out of 800 trajectories contains collision.
50 out of 100 trajectories contains collision.
50 out of 100 trajectories contains collision.
CLNNwC_IPR_Gyro_homo_cor0.8_mu0.1
tensor([[0.1673, 0.6941, 0.6939, 0.7965]], grad_fn=<ExpBackward>)
mu: tensor([0.0998], grad_fn=<ReluBackward0>)
cor:tensor([0.8222], grad_fn=<HardsigmoidBackward>)
